version: 2
jobs:
  build:
      working_directory: /home/circleci/duo-admin
      docker: 
        - image: circleci/node:8.11.1 
      steps:
        - run: git clone https://github.com/FinBook/duo-admin.git
        - run: cd duo-admin
        - run:
            name: install-npm-wee
            command: npm install
        - run: cd ..
        - run: git clone https://github.com/FinBook/duo-contract-wrapper.git
        - run: cd duo-contract-wrapper
        - run:
            name: install-npm
            command: npm install
        - run: cd ~/duo-admin
        - run: # run tests
            name: test
            command: npm test
