version: 2
jobs:
  build:
      working_directory: /home/circleci/duo-admin
      docker: 
        - image: circleci/node:8.11.1 
      steps:
        - checkout
        - run:
            name: npm install admin
            command: npm install
        - run: cd /home/circleci
        - run: git clone https://github.com/FinBook/duo-contract-wrapper.git /home/circleci/duo-contract-wrapper
        - run: cd /home/circleci/duo-contract-wrapper
        - run:
            name: install npm cpnstract wrapper
            command: npm install
        - run: cd ~/duo-admin
        - run: 
            name: test
            command: npm test
