version: 2
jobs:
    build:
        working_directory: /home/circleci/duo-admin
        docker:
            - image: circleci/node:8.11.1
        steps:
            - checkout
            - run:
                  name: npm install admin
                  command: cd /home/circleci/duo-admin && npm install
            - run:
                  name: test coverage
                  command: npm test -- --coverage -w 1 --forceExit
            - run:
                  name: post coverage
                  command: cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
workflows:
    version: 2
    build_and_test:
        jobs:
            - build
    schedule_deploy:
        triggers:
            - schedule:
                  cron: '0 4 * * *'
                  filters:
                      branches:
                          only: master
        jobs:
            - build
