version: 2
jobs:
    build:
        working_directory: /home/circleci/duo-admin
        docker:
            - image: circleci/node:8.11.1
        steps:
            - checkout
            - run:
                  name: npm install admin
                  command: cd /home/circleci/duo-admin && npm install
            - run: git clone https://github.com/FinBook/duo-contract-wrapper.git /home/circleci/duo-contract-wrapper
            - run:
                  name: install npm contract wrapper
                  command: cd /home/circleci/duo-contract-wrapper && npm i -f
            - run: cd ~/duo-admin
            - run:
                  name: test coverage
                  command: npm test -- --coverage -w 1 --forceExit
            - run:
                  name: post coverage
                  command: cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
            - save_cache:
                  key: dependency-test-{{ .Environment.CIRCLE_SHA1 }}
                  paths:
                      - /home/circleci/duo-admin
    deploy:
        docker:
            - image: circleci/python:2.7-jessie
        working_directory: /home/circleci/test
        steps:
            - run:
                  name: Install awscli
                  command: sudo pip install awscli
            - restore_cache:
                  key: dependency-test-{{ .Environment.CIRCLE_SHA1 }}
            - run: aws s3 sync /home/circleci/duo-admin/coverage/lcov-report s3://duo-admin
workflows:
    version: 2
    build_and_test:
        jobs:
            - build
    schedule_deploy:
        triggers:
            - schedule:
                  cron: '0 4 * * *'
                  filters:
                      branches:
                          only: master
        jobs:
            - build
            - deploy:
                  requires:
                      - build
